name: Test Self-Hosted Runner

on: [push]

jobs:
  test:
    runs-on: github-actions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Print environment info
      run: |
        echo "Running on host: $HOSTNAME"
        echo "Python version:"
        python --version
        echo "Pip version:"
        pip --version
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
